/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.thonill;

import static org.junit.jupiter.api.Assertions.fail;

import java.util.HashMap;
import java.util.Random;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.thonill.gui.ApplicationDialog;
import org.thonill.logger.LOG;
import org.thonill.sql.ConnectionInfo;

/**
 * SqlTest provides tests for database connectivity and operations.
 */

public class ApplicationDialogTest extends SqlTest {
	private static final String PASSWORD = "";
	private static final String USER = "sa";
	public static final String url = "jdbc:h2:./build/tmp/test/h2test";
	private static final Random random = new Random();

	@BeforeAll
	public static void AppTestinit() {

		try {
			fillDb();
		} catch (Exception e) {
			LOG.severe(e.getLocalizedMessage());
		}
	}

	private void callMain(String sqlFile, String steuerFile, String templateFile, String outputFile) {
		HashMap<String, String> args = new HashMap<>();
		addResource(args, "dbDatei", "testDb.properties");
		addResource(args, "sqlDatei", sqlFile);
		addResource(args, "steuerDatei", steuerFile);
		addResource(args, "excelVorlage", templateFile);
		addOutput(args, "ausgabeDatei", outputFile);

		new ApplicationDialog().main(args);

	}

	@Test
	public void callMain() {
		callMain("selectRechnungen.sql", null,null, "out1.xls");
	//	callMain("selectRechnungen.sql", null, "RechnungVorlage.xls", "out1.xls");
	}

	private void addResource(HashMap<String, String> args, String key, String fileName) {
		if (fileName != null) {
			args.put(key, getResourcePath(fileName));
		}
	}

	private String getResourcePath(String fileName) {
		return "src\\test\\resources\\" + fileName;
	}

	private void addOutput(HashMap<String, String> args, String key, String fileName) {
		if (fileName != null) {
			args.put(key, getOutputPath(fileName));
		}
	}

	private String getOutputPath(String fileName) {
		return "build/tmp/test" + fileName;
	}
}